spring.application.name=banco-consolidacion

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_consolidacion
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true